#!/usr/bin/env bash
# This Bash script that transfers a file from our client to a server

path_to_file="$1"
ip_address="$2"
username="$3"
path_to_sshkey="$4"

if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$path_to_sshkey" "$path_to_file" "$username"@"$ip_address":~/
fi
