#!/usr/bin/env bash
# Bash script that configures a server so that nginx is running and listening
# on port 80 of all server'sactive IPv4 IPs
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
