#!/usr/bin/env bash
# This script displays "Holberton School" 10 times using while loop

counter=1
while [ $counter -le 10 ]
do
	echo "Holberton School"
	counter=$(( counter + 1 ))
	# less preferred
	# let counter=counter+1
done
