#!/usr/bin/env bash
# This Bash Script loops from 1 to 10:
#      displays "bad luck" for the 4th loop iteration
#      displays "good luck" for the 8th loop iteration
#      displays "Holberton School" fo the other iterations

counter=1
while [ $counter -le 10 ]
do
	if [ $counter -eq 4 ]
	then
		echo "bad luck"
	elif [ $counter -eq 8 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	        counter=$(( counter + 1))
done
