#!/usr/bin/env bash
# Configure ufw to block all incoming traffic, except the TCP ports 22, 80, 443
sudo ufw disable
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
